In [2]:
import pandas as pd

df = pd.read_csv("Dog Data all.csv")

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17840 entries, 0 to 17839
Data columns (total 27 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              17840 non-null  int64
 1   id                      17840 non-null  int64
 2   organization_id         17840 non-null  object
 3   url                     17840 non-null  object
 4   type                    17840 non-null  object
 5   species                 17840 non-null  object
 6   breeds                  17840 non-null  object
 7   colors                  17840 non-null  object
 8   age                     17840 non-null  object
 9   gender                  17840 non-null  object
 10  size                    17840 non-null  object
 11  coat                    4167 non-null   object
 12  attributes              17840 non-null  object
 13  environment             17840 non-null  object
 14  tags                    17840 non-null  object
 15  name                    17840 non-null  object
 16  description             12023 non-null  object
 17  organization_animal_id  13110 non-null  object
 18  photos                  17840 non-null  object
 19  primary_photo_cropped   16266 non-null  object
 20  videos                  17840 non-null  object
 21  status                  17840 non-null  object
 22  status_changed_at       17840 non-null  object
 23  published_at            17840 non-null  object
 24  distance                0 non-null      float64
 25  contact                 17840 non-null  object
 26  _links                  17840 non-null  object
dtypes: float64(1), int64(2), object(24)
memory usage: 3.7+ MB

In [3]:
df_new = df[["species","breeds","colors","age","gender","size","coat","attributes","environment","tags","name"]]

In [117]:
##Data Wrangling

##Spliting breeds attribute to primary, secondary, mixed and unknown

ls = df_new["breeds"].str.split(",", expand=True)

ls.rename(columns = {0:'Primary_breed',
                     1:'Secondary_breed',
                     2:'Mixed_breed',
                     3:'Unknown_breed'}, 
            inplace = True)

ls["Primary_breed"] = ls["Primary_breed"].str.replace("{'primary':","", regex=True)

ls["Secondary_breed"] = ls["Secondary_breed"].str.replace("'secondary': ","", regex=True)

ls["Mixed_breed"] = ls["Mixed_breed"].str.replace("'mixed':","", regex=True)

ls["Unknown_breed"] = ls["Unknown_breed"].str.replace("'unknown': ","", regex=True)

ls["Unknown_breed"] = ls["Unknown_breed"].str.replace("}","", regex=True)

df1 = pd.concat([df_new, ls], axis=1, join="inner")

##Spliting colors attribute to primary, secondary, mixed and unknown

ls1 = df_new["colors"].str.split(":", expand=True)

ls1[1] = ls1[1].str.replace(", 'secondary'","", regex=True)
ls1[2] = ls1[2].str.replace(", 'tertiary'","", regex=True)
ls1[3] = ls1[3].str.replace("}","", regex=True)

ls1.rename(columns = {1:'Primary_color',
                     2:'Secondary_color',
                     3:'Tertiary_color'}, 
            inplace = True)

ls1.drop(columns=0, inplace=True)

df2 = pd.concat([df1, ls1], axis=1, join="inner")

##Spliting attributes to spayed_neutered, house_trained, declawed, special_needs and shots_current

ls2 = df2["attributes"].str.split(",", expand=True)

ls2[0]=ls2[0].str.replace("{'spayed_neutered':","", regex=True)
ls2[1]=ls2[1].str.replace("'house_trained':","", regex=True)
ls2[2]=ls2[2].str.replace("'declawed': ","", regex=True)
ls2[3]=ls2[3].str.replace("'special_needs': ","", regex=True)
ls2[4]=ls2[4].str.replace("'shots_current': ","", regex=True)
ls2[4]=ls2[4].str.replace("}","", regex=True)

ls2.rename(columns = {0:'spayed_neutered',
                     1:'house_trained',
                     2:'declawed',
                     3:'special_needs',
                     4:'shots_current'}, 
            inplace = True)

df3 = pd.concat([df2, ls2], axis=1, join="inner")

##Spliting environment to children, dogs and cats

ls3 = df3["environment"].str.split(",", expand=True)

ls3[0]=ls3[0].str.replace("{'children':","", regex=True)
ls3[1]=ls3[1].str.replace("'dogs': ","", regex=True)
ls3[2]=ls3[2].str.replace("'cats': ","", regex=True)
ls3[2]=ls3[2].str.replace("}","", regex=True)

ls3.rename(columns = {0:'env_children',
                     1:'env_dogs',
                     2:'env_cats'}, 
            inplace = True)

pets_data = pd.concat([df3, ls3], axis=1, join="inner")

pets_data.drop(columns=["breeds","colors","attributes","environment"], inplace=True)

pets_data["tags"] = pets_data["tags"].str.replace("\\[]","N/A",regex=True)

pets_data["coat"] = pets_data["coat"].fillna("N/A")

##Getting rid of name as it doesn't qualify for calculating associations
##species and declawed as no variation in data

pets_data.drop(columns=["name","species","declawed"], inplace=True)

pets_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17840 entries, 0 to 17839
Data columns (total 19 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   age              17840 non-null  object
 1   gender           17840 non-null  object
 2   size             17840 non-null  object
 3   coat             17840 non-null  object
 4   tags             17840 non-null  object
 5   Primary_breed    17840 non-null  object
 6   Secondary_breed  17840 non-null  object
 7   Mixed_breed      17840 non-null  object
 8   Unknown_breed    17840 non-null  object
 9   Primary_color    17840 non-null  object
 10  Secondary_color  17840 non-null  object
 11  Tertiary_color   17840 non-null  object
 12  spayed_neutered  17840 non-null  object
 13  house_trained    17840 non-null  object
 14  special_needs    17840 non-null  object
 15  shots_current    17840 non-null  object
 16  env_children     17840 non-null  object
 17  env_dogs         17840 non-null  object
 18  env_cats         17840 non-null  object
dtypes: object(19)
memory usage: 2.6+ MB

In [118]:
df_dummy = pd.get_dummies(pets_data[['age', 'gender','size','coat','Primary_breed','Secondary_breed','Primary_color','Secondary_color']])

In [119]:
pets_data = pd.concat([df_dummy, pets_data], axis=1, join="inner")

pets_data.drop(columns=['age', 'gender','size','coat','Primary_breed','Secondary_breed','Primary_color','Secondary_color','tags'],
              inplace=True)

In [120]:
ls = ['Mixed_breed','Unknown_breed','Tertiary_color','spayed_neutered','house_trained','special_needs','shots_current','env_children','env_dogs','env_cats']

for i in ls:
    pets_data[i] = pets_data[i].str.strip().apply(lambda x: 1 if x=='True' else 0)

In [121]:
pets_data

,age_Adult,age_Baby,age_Senior,age_Young,gender_Female,gender_Male,size_Extra Large,size_Large,size_Medium,size_Small,...,Mixed_breed,Unknown_breed,Tertiary_color,spayed_neutered,house_trained,special_needs,shots_current,env_children,env_dogs,env_cats
0,0,1,0,0,0,1,0,0,0,1,...,1,0,0,1,0,0,1,1,1,1
1,0,1,0,0,0,1,0,0,0,1,...,1,0,0,1,0,0,1,1,1,1
2,0,1,0,0,1,0,0,0,0,1,...,1,0,0,1,0,0,1,1,1,1
3,0,1,0,0,1,0,0,0,0,1,...,1,0,0,1,0,0,1,1,1,1
4,1,0,0,0,1,0,0,0,0,1,...,1,0,0,1,0,0,1,0,1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17835,0,0,0,1,0,1,0,1,0,0,...,1,0,0,1,0,0,1,0,1,0
17836,0,1,0,0,1,0,0,0,0,1,...,1,0,0,0,1,0,1,1,1,1
17837,0,1,0,0,1,0,0,0,1,0,...,1,0,0,1,0,0,1,0,0,0
17838,0,0,0,1,0,1,0,0,1,0,...,1,0,0,1,0,0,1,0,1,0
17839,0,0,0,1,0,1,0,0,0,1,...,0,0,0,1,0,0,0,0,0,0

In [157]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth


frequent_itemsets = apriori(pets_data, min_support=0.1, use_colnames=True)
### alternatively:
#frequent_itemsets = apriori(df, min_support=0.6, use_colnames=True)
#frequent_itemsets = fpmax(df, min_support=0.6, use_colnames=True)

frequent_itemsets

from mlxtend.frequent_patterns import association_rules

ar_data = association_rules(frequent_itemsets, metric="confidence", min_threshold=0.8)

In [158]:
ar_data.sort_values(by=['lift'],ascending=False).head(25)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
140,(env_cats),"(env_dogs, env_children)",0.126009,0.228531,0.105830,0.839858,3.675021,0.077033,4.817393
138,"(env_dogs, env_cats)",(env_children),0.122085,0.243554,0.105830,0.866850,3.559174,0.076095,5.681172
163,"(age_Baby, env_dogs, Mixed_breed)",(env_children),0.120628,0.243554,0.103419,0.857342,3.520134,0.074040,5.302515
20,(env_cats),(env_children),0.126009,0.243554,0.107287,0.851423,3.495833,0.076597,5.091291
167,"(age_Baby, env_dogs, shots_current)",(env_children),0.130549,0.243554,0.111043,0.850580,3.492368,0.079247,5.062538
33,"(age_Baby, env_dogs)",(env_children),0.144226,0.243554,0.121413,0.841819,3.456398,0.086286,4.782152
166,"(age_Baby, env_children)","(env_dogs, Mixed_breed)",0.122702,0.244339,0.103419,0.842851,3.449519,0.073439,4.808555
170,"(age_Baby, env_children)","(env_dogs, shots_current)",0.122702,0.294002,0.111043,0.904979,3.078138,0.074968,7.429948
439,"(spayed_neutered, Mixed_breed, env_children)","(env_dogs, shots_current)",0.119451,0.294002,0.104821,0.877522,2.984747,0.069702,5.764296
34,"(age_Baby, env_children)",(env_dogs),0.122702,0.332343,0.121413,0.989493,2.977324,0.080633,63.543525
165,"(age_Baby, Mixed_breed, env_children)",(env_dogs),0.104596,0.332343,0.103419,0.988746,2.975076,0.068657,59.326089
169,"(age_Baby, shots_current, env_children)",(env_dogs),0.112332,0.332343,0.111043,0.988523,2.974405,0.073710,58.173240
139,"(env_cats, env_children)",(env_dogs),0.107287,0.332343,0.105830,0.986416,2.968065,0.070174,49.149823
136,"(env_cats, shots_current)",(env_dogs),0.108744,0.332343,0.106278,0.977320,2.940695,0.070138,29.437602
342,"(spayed_neutered, env_children)","(env_dogs, shots_current)",0.161603,0.294002,0.138957,0.859868,2.924699,0.091446,5.038098
21,(env_cats),(env_dogs),0.126009,0.332343,0.122085,0.968861,2.915244,0.080207,21.441326
335,"(Mixed_breed, env_children)","(env_dogs, shots_current)",0.186099,0.294002,0.159361,0.856325,2.912649,0.104648,4.913863
232,"(gender_Male, env_children)","(env_dogs, shots_current)",0.118834,0.294002,0.100953,0.849528,2.889530,0.066015,4.691897
323,"(Secondary_color_ None, Mixed_breed, env_child...",(env_dogs),0.130381,0.332343,0.125112,0.959587,2.887340,0.081781,16.520958
434,"(Secondary_color_ None, shots_current, Mixed_b...",(env_dogs),0.113453,0.332343,0.108857,0.959486,2.887035,0.071151,16.479728
262,"(size_Medium, env_children)","(env_dogs, shots_current)",0.122478,0.294002,0.103924,0.848513,2.886075,0.067915,4.660438
120,"(Mixed_breed, env_children)",(env_dogs),0.186099,0.332343,0.177915,0.956024,2.876618,0.116066,15.182336
334,"(shots_current, Mixed_breed, env_children)",(env_dogs),0.166760,0.332343,0.159361,0.955630,2.875433,0.103939,15.047571
92,"(coat_N/A, env_children)",(env_dogs),0.112444,0.332343,0.107343,0.954636,2.872442,0.069973,14.717800
137,(env_cats),"(env_dogs, shots_current)",0.126009,0.294002,0.106278,0.843416,2.868741,0.069231,4.508758